import { requireCustomerTenant } from "@/lib/customer-os/server";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import Link from "next/link";

type ImportListItem = { id: string; status: string; source_type: string; source_name: string; file_name: string | null; total_rows: number; exact_match_count: number; probable_match_count: number; ambiguous_count: number; new_customer_count: number; rejected_count: number; created_at: string };

export default async function ImportsPage() {
  const { tenantId } = await requireCustomerTenant(["super_admin", "manager"]);
  const supabase = await createSupabaseServerClient();
  const { data: imports, error } = await supabase.from("import_batches").select("id,status,source_type,source_name,file_name,total_rows,exact_match_count,probable_match_count,ambiguous_count,new_customer_count,rejected_count,validation_error_count,planned_mutation_count,created_at").eq("tenant_id", tenantId).order("created_at", { ascending: false }).limit(100);
  if (error) throw new Error("Unable to load imports");
  const importRows = (imports ?? []) as ImportListItem[];
  return <main className="admin-main"><div className="page-heading"><div><p className="eyebrow">IMPORT REVIEW CONTROL</p><h1>Import batches</h1><p className="lede">Files are parsed in memory, dry-run classified and held for review. Database import execution is locked.</p></div><Link className="primary-button" href="/admin/imports/new">New dry run</Link></div><section className="table-card"><div className="table-scroll"><table><thead><tr><th>Source</th><th>Status</th><th>Rows</th><th>Matches</th><th>Review</th><th>Created</th></tr></thead><tbody>{importRows.map((item) => <tr key={item.id}><td><Link className="table-link" href={`/admin/imports/${item.id}`}>{item.source_name}</Link><small>{item.file_name ?? item.source_type}</small></td><td><span className="state-pill">{item.status}</span></td><td>{item.total_rows}</td><td>{item.exact_match_count} exact · {item.probable_match_count} probable</td><td>{item.ambiguous_count} ambiguous · {item.rejected_count} rejected</td><td>{new Date(item.created_at).toLocaleDateString("en-GB")}</td></tr>)}{importRows.length === 0 && <tr><td colSpan={6} className="empty-state">No dry-run imports yet.</td></tr>}</tbody></table></div></section><section className="detail-card full-width-card"><h2>Historical dataset reconciliation gate</h2><p className="muted">Read-only evidence from the validated Phase 2 offline dry-run. The raw workbook and customer rows are not stored in this panel.</p><div className="metric-grid"><article className="metric"><span>Unique manual-review records</span><strong>225</strong></article><article className="metric"><span>Rejected rows</span><strong>46</strong></article><article className="metric"><span>Probable matches</span><strong>39</strong></article><article className="metric"><span>Ambiguous matches</span><strong>31</strong></article><article className="metric"><span>Mixed identity-field flags</span><strong>113</strong></article><article className="metric"><span>Review flags</span><strong>229</strong><small>Four flags overlap across records.</small></article><article className="metric"><span>Estimated unique customers</span><strong>1,133–1,152</strong></article><article className="metric"><span>Historical expectation</span><strong>~1,161</strong><small>9–28 record gap remains unresolved.</small></article></div><p className="warning-box">IMPORT LOCKED: a final manual-review resolution report, canonical-file reconciliation and explicit owner approval are required before a future migration restores import execution permission.</p></section></main>;
}
